export default [
  'Andrzej Duda',
  'Arnold Schwarzenegger',
  'Barack Obama',
  'Britney Spears',
  'Bill Gates',
  'Donald Trump',
  'Elon Musk',
  'George Bush',
  'Guido van Rossum',
  'Jan Pawel II',
  'Johnny Depp',
  'Kim Dzong Un',
  'Mark Zuckerberg',
  'Michael Jackson',
  'Steve Jobs',
  'Sylvester Stallone',
  'Vladimir Putin',
];
